inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Rails/RefuteMethods:
  Enabled: false